### ISSUE TITLE
No Umquilt logo in Windows

### ISSUE THREAD

**Issue by HelenaMKG** [Umtility/umquilt#18]
Yeah, we have cool icons, but we have yet to implement a logo in the small batch file.

The way batch works is shit: it prints quotes in echo statements, just looks way too ugly to put in the finished program, so i got rid of it and replaced it with a joke. However, we gotta find a solution for this. I don't wanna embed the logo in the program, and no, the first result on StackOverflow does not work.﻿

**Comment by ImperatorStorm** [comment]
```
echo "   _    _                       _ _ _         
echo "  | |  | |                     (_) | |        
echo "  | |  | |_ __ ___   __ _ _   _ _| | |_       
echo "  | |__| | | | | | | (_| | |_| | | | |_ _     
echo "   \____/|_| |_| |_|\__, |\__,_|_|_|\__(_)    
echo "                       | |
echo "                       |_|
echo.
echo.
echo.
```
It'll still have the `"`, but it works otherwise
prints as
```
"   _    _                       _ _ _
"  | |  | |                     (_) | |
"  | |  | |_ __ ___   __ _ _   _ _| | |_
"  | |__| | | | | | | (_| | |_| | | | |_ _
"   \____/|_| |_| |_|\__, |\__,_|_|_|\__(_)
"                       | |
"                       |_|
```

**Comment by HelenaMKG** [comment]
Thanks.
